spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: local.123
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl:
        auto: update
