spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/agilesyncdb
    username: postgres
    password: local.123
    driverClassName: org.postgresql.Driver
    maximumPoolSize: 5
  jpa:
    show-sql: true
api:
  security:
    token:
      secret: ${JWT_SECRET:ezxi3zqSe5}
